### ISSUE TITLE
Zipkin with ES7 - Cannot invoke "String.hashCode()" because "<local3>" is null

### ISSUE THREAD

**Issue by yzdann** [openzipkin/zipkin#3400] opened 2021-12-06 15:06 UTC
## Zipkin2 with ES7 - Cannot invoke "String.hashCode()" because "<local3>" is null

Hi!
We have this issue since we upgrade our zipkin backend storage from es6 to es7.

Cannot invoke "String.hashCode()" because "<local3>" is null
![ss2](https://user-images.githubusercontent.com/22779039/144869527-5abcef82-a664-4392-9595-5a30853991f9.png)

![ss](https://user-images.githubusercontent.com/22779039/144869524-6e7a9bef-fca6-44d3-becf-13b30902763a.png)
 

```java
2021-12-06 14:46:10.488 WARN [/] 1 --- [orker-epoll-2-1] z.s.i.BodyIsExceptionMessage : Unexpected error handling request.
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local3>" is null
at zipkin2.elasticsearch.internal.JsonSerializers.parseSpan(JsonSerializers.java:67) ~[zipkin-storage-elasticsearch-2.23.9.jar:?]
at zipkin2.elasticsearch.internal.client.SearchResultConverter.convert(SearchResultConverter.java:46) ~[zipkin-storage-elasticsearch-2.23.9.jar:?]
at zipkin2.elasticsearch.internal.client.SearchResultConverter.convert(SearchResultConverter.java:27) ~[zipkin-storage-elasticsearch-2.23.9.jar:?]
at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:275) ~[zipkin-storage-elasticsearch-2.23.9.jar:?]
at zipkin2.elasticsearch.internal.client.HttpCall.doExecute(HttpCall.java:166) ~[zipkin-storage-elasticsearch-2.23.9.jar:?]
at zipkin2.Call$Base.execute(Call.java:391) ~[zipkin-2.23.9.jar:?]
at zipkin2.Call$FlatMapping.doExecute(Call.java:276) ~[zipkin-2.23.9.jar:?]
at zipkin2.Call$Base.execute(Call.java:391) ~[zipkin-2.23.9.jar:?]
at zipkin2.Call$Mapping.doExecute(Call.java:237) ~[zipkin-2.23.9.jar:?]
at zipkin2.Call$Base.execute(Call.java:391) ~[zipkin-2.23.9.jar:?]
at zipkin2.Call$Mapping.doExecute(Call.java:237) ~[zipkin-2.23.9.jar:?]
at zipkin2.Call$Base.execute(Call.java:391) ~[zipkin-2.23.9.jar:?]
at zipkin2.server.internal.ZipkinQueryApiV2.getTraces(ZipkinQueryApiV2.java:147) ~[classes/:?]
at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:391) ~[armeria-1.13.3.jar:?]
at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$8(AnnotatedService.java:359) ~[armeria-1.13.3.jar:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:547) ~[armeria-1.13.3.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.69.Final.jar:4.1.69.Final]
at java.lang.Thread.run(Unknown Source) [?:?]
```

## Steps to Reproduce
Zipkin: ghcr.io/openzipkin/zipkin:2
ES: 7.13.4

**Comment by jcchavezs** [comment] 2021-12-06 19:09
Ping @xeraa

**Comment by xeraa** [comment] 2021-12-06 23:27
Hmmm. If I'm not mistaken, Zipkin has written it's own Elasticsearch client, so my knowledge here will be very shallow.

I assume we're talking about https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/JsonSerializers.java#L67? I don't think that's really on the Elasticsearch side (which is not a solution, I know 😕)

**Comment by yzdann** [comment] 2021-12-08 07:39
More details:

Response:
![response](https://user-images.githubusercontent.com/22779039/145167272-3551d381-d6a4-4349-9316-726c3b2f4f44.png)


Indices:
![image](https://user-images.githubusercontent.com/22779039/145166643-5e040b13-62b1-4cd7-9da6-2eb73625e7e8.png)

Role (We gave more than what it needs!):
![image](https://user-images.githubusercontent.com/22779039/145167358-984fc9aa-b54f-4fad-8657-58bbfa70e4db.png)

Mappings:
![image](https://user-images.githubusercontent.com/22779039/145207010-21ea2fdc-6d83-4bb8-b3e7-f822f2c1fdfb.png)

**Comment by xeraa** [comment] 2021-12-08 17:50
Yes, I don't think this is an Elasticsearch issue — you can write and read data. The problem is somewhere in the Zipkin codebase visualizing the data and it runs into a NPE (maybe some missing field; not exactly sure).

**Comment by yzdann** [comment] 2021-12-20 11:34
I removed ILM from Zipkin indices, and everything works fine!

**Comment by xeraa** [comment] 2021-12-21 22:01
Interesting. Did you use a specific policy? Maybe making the index read-only was causing issues? But it's just a wild guess.

**Comment by MonsterOli** [comment] 2022-04-04 22:14
FYI, there's a fix waiting in PR for this issue: https://github.com/openzipkin/zipkin/pull/3437

**Comment by yzdann** [comment] 2022-04-05 10:54
> Interesting. Did you use a specific policy? Maybe making the index read-only was causing issues? But it's just a wild guess.

Sorry for my late response. I don't have access to that environment anymore.

**Comment by codefromthecrypt** [comment] 2024-04-16 07:21
closing this as it is very out-of-date, and the related issue hinted at a non-standard setup.

**Closed as completed by codefromthecrypt** 2024-04-16 07:21 UTC
Labels: bug
