### ISSUE TITLE
Allow specification of "Start Time" in web search UI

### ISSUE THREAD

**Issue by mjbryant** [openzipkin/zipkin#1065] opened 2016-03-25 17:39 UTC
Sometimes it's nice to be able to narrow down your search a bit more. The absence of this feature always seemed a bit.. odd.

**Comment by eirslett** [comment] 2016-03-26 17:23
Is it implemented in the API backends yet?

**Comment by eirslett** [comment] 2016-03-26 17:25
But I believe this issue is a duplicate of #1063 ?

**Closed as completed** 2016-03-29 01:13 UTC
Labels: enhancement, ui
