### ISSUE TITLE
[Zipkin-ui] External tomcat and js

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin#1552] opened 2017-04-06 07:40 UTC
When i deployed a war with zipkin-ui-autoconfigure in tomcat container with a context path (value zipkin)
I have 404 when i request for js file.
Indeed, js script was loaded at root context path by index.html

http://host:port/app/min/..../script.js
scripts js was at http://host:port/ZIPKIN/app/min/..../script.js

Can you add the context path in index.html for js ressources ? (ex window.location)

Regards
Gaetan BOGAERT

**Comment by eirslett** [comment] 2017-04-06 07:50
I'll close this issue since it's a duplicate of #1229.

**Closed as completed by eirslett** 2017-04-06 07:50 UTC
Labels: question, ui
